### ISSUE TITLE
insstall isue on 2.1.0.1

### ISSUE THREAD

**Issue by PXLTCH** [multimerch/multimerch#117]
i dont use vqmod and i want to update all files manually but how to create database? is there any sql file to create database ? without vqmod many isue and not working.

**Comment by ffctcc** [comment]
Database definitions are available in the admin/model/multiseller/install.php file. However, MultiMerch will not work without vQmod. There are over 80Kb of vQmod code in just MultiMerch Core and we update it often.

Turning it into manual modifications to OpenCart Core is neither recommended nor viable since it will prevent you from updating both MultiMerch and OpenCart in the future.

There are no downsides of using vQmod so we strongly suggest you go with it. Alternatively, you may want to convert our vQmod changes into OCMOD (which is built into OpenCart) if you absolutely want to not use vQmod. They are similar and will make it much easier to maintain your store in the future.

**Comment by PXLTCH** [comment]
i have created database , but I dont want to use any vqmod or ocmod , both very danger for us and for system and i want to use only manualy code ,we changed and updated in your web site too much core code and any vqmod or ocmod file will not work in my web  site because of code line and names change.
vqmod search function will not find searched code to add or replace

 i updated already all your code to manualy by hand to my opencart core but still no work, where we must change ?

for example i changed all places where used like "" require_once(VQMod::modCheck(DIR_SYSTEM . 'library/msloader.php')); ""  also but still have error.

in front end we have this error

Notice: Trying to get property of non-object in C:\xampp\htdocs\catalog\controller\common\header.php on line 5
Fatal error: Call to a member function getTotalProducts() on a non-object in C:\xampp\htdocs\catalog\controller\common\header.php on line 5


and in the back side we have this error
Notice: Undefined property: Loader::$load in C:\xampp\htdocs\admin\view\template\common\header.tpl on line 186
Fatal error: Call to a member function model() on a non-object in C:\xampp\htdocs\admin\view\template\common\header.tpl on line 186
