### ISSUE TITLE
database reset on upgrade

### ISSUE THREAD

**Issue by curiousPup** [multimerch/multimerch#67]
i upgraded from MM7 to 7.1 and it reset all the multimerch related tables in my database. 
Did I make a mistake somewhere or it is supposed to work like that?

**Comment by ffctcc** [comment]
No, that shouldn't happen. How did you upgrade exactly and what happened with the tables (did they get removed or are they empty)?

**Comment by curiousPup** [comment]
they r empty..
i simply downloaded the latest version and replace my files with new ones. then there appeared an link to upgrade the database at the top of my multimerch settings page. I followed that link and what happened after that is what i have already told u

**Comment by curiousPup** [comment]
i found the reason behind it. it happened as i uninstalled and installed again the MM module from back end since it failed to upgrade properly. That is why database got created again.
thanks anyways

**Comment by ffctcc** [comment]
What version were you upgrading from? This version upgrade process has been in MultiMerch since August 2014 (pre-OC2) and none of our clients has experienced any issues with it.

It couldn't have been caused by the MultiMerch upgrade script as we don't have any DB function calls that modify data inside the main database inside it for security purposes, only code that creates new tables and inserts the database version information, so the only way it can happen is when you reinstall MultiMerch completely via Admin > Extensions > Modules > [Uninstall / Install] buttons.

You can see the upgrade file itself here: https://github.com/multimerch/multimerch/blob/master/upload/admin/model/multiseller/upgrade.php

Please mail your complete information (including your OC/MM versions and what versions were you upgrading from) along with all relevant accesses to support@multimerch.com and we'll take a look.

**Comment by ffctcc** [comment]
Yes, I see it was the case indeed. Uninstalling does indeed remove all MultiMerch-related data including the DB so you shouldn't do it unless this is your intention.
