### ISSUE TITLE
Product Add Validation Error

### ISSUE THREAD

**Issue by satyajit9830** [multimerch/multimerch#68]
Hello, When i m trying to add new product from seller dashboard, its showing error.
"Error occured when submitting the form. Please contact the store owner for more information."
Also in firefox consol its showing some email error.
But when i m trying to check the product list from seller dashboard, its showing that the product has been added and its activated.
I have disabled auto product listing in admin.

**Comment by pawanchauhan05** [comment]
same here..

**Comment by ffctcc** [comment]
This was a bug related to OpenCart 2.0, but this can also be caused by a number of other reasons. 

If you are having this issue with the latest versions of MultiMerch, check our Admin > MultiMerch > Debug output and see our entry about form submission errors at https://multimerch.com/docs/common-problems/.
