### ISSUE TITLE
Spacial Pirce Not Working Proper

### ISSUE THREAD

**Issue by anuj1993** [multimerch/multimerch#69]
When i Add Spacial Price In Product And Purchase The product Then Price Doubled in Shopping cart.
Example : Product Price - 399
                 Spacial Price - 199
                 Option- Size- M -> Price 199
                                       L- -> Price 199
when purchase with different account it add 399+199 = 598 in Shopping Cart And Made Payment 598 + tax.
I am also check on your demo site. i was create product as vendor1 in mp3 player ->text 9 and purchase it as guest. Same Problem Appear There. The Product Name "Cherokee Men's Round Neck Cotton T-Shirt"
Thanks In Advance.

**Comment by ffctcc** [comment]
This is because OpenCart2 makes it possible to specify different special prices for different customer groups. The default customer group used by MultiMerch is also the guest group, so if you change or remove it your guests won't be able to see special prices. Therefore you shouldn't remove OpenCart's default customer group.

**Comment by anuj1993** [comment]
Then how I'm solve this problem.
Should I delete default customer group and make different group or only make another customer group.

**Comment by ffctcc** [comment]
Technically, you should keep the default customer group and then add a different one for specific customer types. We'll implement a possibility for sellers to choose a customer group with their product specials in one of the coming releases.

**Comment by ffctcc** [comment]
This is now available in the latest version of MultiMerch.
