### ISSUE TITLE
Invoice Assignment

### ISSUE THREAD

**Issue by satyajit9830** [multimerch/multimerch#79]
Hi,
Is this possible to assign invoice to seller ?
Please have a system by which an order/invoice can be assigned to seller

**Comment by ffctcc** [comment]
We are working on a separate invoicing system for vendors. Assigning orders
to vendors isn't possible at the moment because the whole fee/commission
calculation and balance transactions are created during order creation and
it's not possible to modify those afterwards. Unfortunately, there is no
simple workaround to this.

**Comment by ffctcc** [comment]
New invoicing system will be available in the next update.
