### ISSUE TITLE
Error occured when submitting the form. Please contact the store owner for more information.

### ISSUE THREAD

**Issue by gajendrasingh1** [multimerch/multimerch#95]
Sir i changed in msmail.php file. but it is not working please help me

**Comment by ffctcc** [comment]
Please attach your OpenCart error log file.

**Comment by ffctcc** [comment]
This was a bug related to OpenCart 2.0, but this can also be caused by a number of other reasons.

If you are having this issue with the latest versions of MultiMerch, check our Admin > MultiMerch > Debug output and see our entry about form submission errors at https://multimerch.com/docs/common-problems/.
