### ISSUE TITLE
Error occured when submitting the form. Please contact the store owner for more information

### ISSUE THREAD

**Issue by bimalesh2007** [multimerch/multimerch#99]
I have installed opencart 2.0 and latest multimerch extension on godaddy server. I am getting this error: Error occured when submitting the form. Please contact the store owner for more information.. All features are working perfectly except registration. Would you please help me to resolve the issue.

**Comment by ffctcc** [comment]
This was a bug related to OpenCart 2.0, but this can also be caused by a number of other reasons.

If you are having this issue with the latest versions of MultiMerch, check our Admin > MultiMerch > Debug output and see our entry about form submission errors at https://multimerch.com/docs/common-problems/.
